# Generated by Django 3.2.13 on 2022-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='image')),
                ('image', models.ImageField(upload_to='')),
                ('id_image', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Place')),
                ('details_place', models.TextField(verbose_name='Места')),
                ('title_place', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('placeId', models.CharField(max_length=250, verbose_name='ID проекта')),
            ],
        ),
    ]
