# Generated by Django 4.0.6 on 2022-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='id_image',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
