# Generated by Django 4.0.6 on 2022-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_placeimage_id_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['image_id'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображение мест'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение'),
        ),
    ]
