# Generated by Django 4.0.6 on 2022-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='изображение'),
        ),
    ]
